### ISSUE TITLE
PDF download links to Makecode PDF

### ISSUE THREAD

**Issue by cminter** [nominetresearch/microbit-networking-book-python#21]
In the [Introductions Editions section](https://microbit.nominetresearch.uk/networking-book-online-python/#editions), the PDF download button for Python links to the Makecode PDF.

**Comment by ciseng** [comment]
These are indeed referring to the Makecode version: "The online edition of the Makecode version of this book is available from the Nominet Research's website at https://microbit.nominetresearch.uk/networking-book-online/. A PDF version of the same book is available for download."
We do not have a PDF version for the Python.

**Comment by ciseng** [comment]
Modified the editions section so that it clearly talks about the Makecode version.

**Comment by cminter** [comment]
Thanks for the explanation
